name: Build kernel a14-6-1

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "Select KernelSU variant"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "Select KernelSU branch"
        required: true
        type: choice
        options:
          - Stable
          - Dev
          - Other
        default: Dev
      version:
        description: 'Custom version suffix (e.g. text after 6.1.93; leave blank to use default)'
        required: false
        type: string
      use_zram:
        description: 'Enable additional ZRAM algorithms?'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: 'Enable KPM feature?'
        required: true
        type: boolean
        default: true
      get_manager:
        description: 'Also download the latest KSU manager? (Experimentalâ€”turn off if it errors)'
        required: true
        type: boolean
        default: true
      BBG:
        description: 'Enable kernel-level LSM protection for critical partitions/dev nodes?'
        required: true
        type: boolean
        default: true
jobs:

  build-kernel-a14-6-1:
    uses: ./.github/workflows/kernel-a14-6.1.yml
    secrets: inherit
    with:
      make_release: false
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
      BBG: ${{ inputs.BBG }}
  get-ksu-manager:
    if: ${{ inputs.get_manager }}
    uses: ./.github/workflows/get-manager.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant }}

